language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: Running Test
      script:
        - echo $USER
        - npm run test
    - stage: Building Images
      script:
        - echo "build images here"
    - stage: Deploy
      script:
        - echo "deployment configuration here"

        
    
