language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
jobs:
  include:
    stage: Running Test
      script:
        - echo $USER
        - npm run test
    stage: Building Images
        - echo "build images here"
    stage: Deploy
        - echo "deployment configuration here"
